### ISSUE TITLE
Inter font not loading on vercel

### ISSUE THREAD

**Issue by Sxyntheon** [ixhbinphoenix/bne#29]
The Inter font is not loading on desktop when opening the vercel deployment.
Oddly enough it is working on mobile (safari) and localhost on desktop.

Recreate:
Open https://bne-git-frontendfixes-ixhbinphoenix.vercel.app

Open Dev Console and see the error

Fix:
Find out why the font doesn't load on vercel.

**Comment by ixhbinphoenix** [comment]
ey ne ey

**Comment by ixhbinphoenix** [comment]
We needed a new Solution for this anyway, this static content is really clogging up our bandwith usage
![Vercel bandwith usage data](https://cdn.upload.systems/uploads/zuFh4rIF.png)

**Comment by Sxyntheon** [comment]
Fontsources really got my back here. I am pretty sure it finally works now and it could even save some bandwidth because it only loads implicitly used font varients.
