### ISSUE TITLE
wrong grammar used at index page

### ISSUE THREAD

**Issue by renkertm** [ixhbinphoenix/bne#31]
"Dein Tag auf einen Blick" ist falsch. Dein im Akkusativ ist "deinen". Richtig wäre dementsprechend: "Deinen Tag auf einen Blick" [[1]](https://deutsch.lingolia.com/de/grammatik/pronomen/possessivpronomen)

**Comment by Sxyntheon** [comment]
Das stimmt zwar, allerdings steht "dein" nicht im Akkusativ. Der Satz ist verkürzt von "Hier ist dein Tag auf einen Blick". Deswegen ist der Nominativ korrekt.
