### ISSUE TITLE
serviceWorker not included in SSR-bundle

### ISSUE THREAD

**Issue by Sxyntheon** [ixhbinphoenix/bne#50]
The .ts files including the service Worker aren´t bundled on build, because they aren´t imported anywhere, but only loaded during runtime. Therefore they don´t exist in the finished bundle.

Recreation:

Start pnpm preview with node as the serverless adapter.
Open dev tools and get the 404 error

Fixes:
Find a good way to include the files in the finished bundle.
The best approach to me currently is to change the rollup config into bundling the files seperatly

**Comment by ixhbinphoenix** [comment]
[just gonna leave this here...](https://github.com/vite-pwa/astro)

**Comment by Sxyntheon** [comment]
Looks like the files are also not included in the dev build, because they don't appear in the page directory. My guess is that they are not bundled, but can be requested from the local hard drive. Importing the script into another file also doesn't seem to work, because that just copies the whole file into the other on buildtime. Maybe it is possible to host the file on something like serviceworker.theschedule.de
but that isn't really pretty

**Comment by Sxyntheon** [comment]
Alright, I have tested some configurations with rollup-plugins and it seems like the files are not processed by rollup, therefore making it hard to manipulate them. Easiest way now would be to try vite-pwa-astro out
