### ISSUE TITLE
PWA Icons corrupted on Vercel Deployment

### ISSUE THREAD

**Issue by Sxyntheon** [ixhbinphoenix/bne#51]
The PWA Icons can not be loaded in vercel deployments because the files are corrupted.
Building and running local doesn´t produce this error.

My first guess would be that Vercel handles png images in a special way that breaks them in our case.

I´d like someone else take a look at this to verify if I missed something.

**Comment by Sxyntheon** [comment]
Looks like pngs also don´t work when they are used in the page itself.
We could maybe try to host pngs on a different platform instead

**Comment by ixhbinphoenix** [comment]
Well, we have an nginx server now, we can just host those images there.

**Comment by Sxyntheon** [comment]
Fix was to change git behaviour on pngs, which was trying to change lineendings to lf for whatever reason
